var app=new Vue({
  el:'#Deposit',
	data:{
		user:{
			name:'111',
			money:'0.00',
		},
		bank:0,
		withdrawmoney:'',
		withdrawcode:'',
		pic:'https://m8.3000ms.com/official/images/white/avatar.png',
		activetab:0,
		depositlisit:[
			{icon:'https://data.ehometd.com/files/0/92/2585.1531880574png?v=6024',title:'在线支付',
			introduce:'支持32家银行,转账更便捷'},
			{icon:'https://data.ehometd.com/files/0/92/2586.1531880688jpg?v=5776',title:'银行转账',
			introduce:'闲暇存款，您的首选'},
			{icon:'https://data.ehometd.com/files/0/92/2587.1531880773jpg?v=49582',title:'QQ钱包',
			introduce:'简易、快捷、到账不操心'},
		]
	},
	methods:{
		back(){
			window.location.href="index.html"
		},
		detaillist(item){
			if(item.title='在线支付'){
				window.location.href="payment.html"
			}
		},
		addbank(){
			window.location.href="addbank.html"
		},
		changebank(e){
			this.bank=e;
		}
	}
})