var app=new Vue({
  el:'#User',
	data:{
		openSimple:true,
		notice:'重要通告：VIP入款【浦发银行庞高3373】【工商银行马金山1106】已停用；公司会不定期对银行账号进行更换，请您每次入款前务必登录您的会员账号在我们网站获取最新的入款账号，先提交订单再存款，如转入停用账户造成的资金损失本公司概不负责，如有任何疑问请联系我们24小时在线客服。',
		pic:'https://m8.3000ms.com/official/images/white/avatar.png',
		user:{
			name:'1111',
			money:'0.00',
			viplevel:'普通会员',
			gamelevel:[
				{img:'https://m8.3000ms.com/official/images/g-sgj.png',level:0},
				{img:'https://m8.3000ms.com/official/images/g-egame.png',level:0},
				{img:'https://m8.3000ms.com/official/images/g-maya.png',level:0},
				{img:'https://m8.3000ms.com/official/images/g-ag.png',level:0},
			],
		},
		menulist:[
			{img:'https://m8.3000ms.com/official/images/white/menu-profile.png',text:'个人资料'},
			{img:'https://m8.3000ms.com/official/images/white/menu-message.png',text:'信息中心'},
			{img:'https://m8.3000ms.com/official/images/white/menu-modifypwd.png',text:'修改密码'},
			{img:'https://m8.3000ms.com/official/images/white/menu-funds.png',text:'资金管理'},
			{img:'https://m8.3000ms.com/official/images/white/menu-transfer.png',text:'转账'},
			{img:'https://m8.3000ms.com/official/images/white/menu-bankaccount.png',text:'银行账号'},
			{img:'https://m8.3000ms.com/official/images/white/menu-record.png',text:'投注记录'},
			{img:'https://m8.3000ms.com/official/images/white/menu-service.png',text:'客服'},
			{img:'https://m8.3000ms.com/official/images/white/menu-activity.png',text:'优惠活动'},
			{img:'https://m8.3000ms.com/official/images/white/menu-recommend.png',text:'推广代理'},
		]
	},
	methods:{
		seedetail(item){
			if(item.text=='个人资料'){
				window.location.href="userinfo.html"
			}
		},
		back(){
			window.location.href="index.html"
		}
	}
})